### ISSUE TITLE
Input Cloud Point type

### ISSUE THREAD

**Issue by xiaolongDGitHub** [STORM-IRIT/OpenGR#107]
Thanks your repository, the PCLwapper  demo or  super4PCS.exe demo ,the Input cloud Point format is .obj  ,i want to ask how to use the .pcd format  or other format  no normal information ?

**Comment by nmellado** [comment]
Dear @xiaolongDGitHub ,

This app can also load ply files with normals.
Best option to try it: export the ply (binary or text) from Meshlab: I know that their exporter produce files that we can load.
Alternatively, you can also use the PCL example, and modify it to load pcd files.

**Comment by xiaolongDGitHub** [comment]
thanks，i found the demo with PCL，input cloud without normals sper4pcs&nbsp; is also ok.



---Original---
From: "Nicolas ***@***.***&gt;
Date: Fri, Nov 5, 2021 01:10 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [STORM-IRIT/OpenGR] Input Cloud Point type (Issue #107)




 
Dear @xiaolongDGitHub ,
 
This app can also load ply files with normals.
 Best option to try it: export the ply (binary or text) from Meshlab: I know that their exporter produce files that we can load.
 Alternatively, you can also use the PCL example, and modify it to load pcd files.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
