### ISSUE TITLE
PCL Wrapper Compilation and Boost

### ISSUE THREAD

**Issue by zhouchuangchuang** [STORM-IRIT/OpenGR#11]
Hi,

Thank you for your share. But when I use PCL Wrapper, I have some problems.  I have installed PCL, Eigen, OpenCV and Boost, but when I use PCLWrapper in demos of Super4PCS-Master, there are some problems.
First question is that the programm can't find the shared4pcs.h. So I put all the .h files that the programm need in a folder, and the question has been solved, but I don't know whether it is right or not.

The second question is that Severity	Code	Description	Project	File	Line	Suppression State
Error	C2248	'pcl::io::ply::ply_parser::scalar_property_definition_callbacks_type::callbacks_element<U1>': cannot access private struct declared in class 'pcl::io::ply::ply_parser::scalar_property_definition_callbacks_type'	Super4PCS-PCLWrapper	D:\Program Files (x86)\PCL 1.8.1\3rdParty\Boost\include\boost-1_64\boost\mpl\aux_\preprocessed\plain\inherit.hpp	23	

May you help me? (Perhaps my questions is so stupid.. sorry)

**Comment by zhouchuangchuang** [comment]
Hi, I have solved the second problem by modifying ply_parser.h to declare the 'callbacks_element' member of the 'list_property_definition_callbacks_type' and 'scalar_property_definition_callbacks_type' classes as public instead of private.

But there is another problem after I solve the second problem, it says Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file '“super4pcs_algo.lib”'	Super4PCS-PCLWrapper	E:\1.1HIWI\1\1.new\LINK	1	


Are there some connections between the both question?

**Comment by nmellado** [comment]
Hi,
Thanks for your report
Can you confirm you use the `master` branch, and give me your compiler version ?

Also, is this problem still occurring if you use the branch `algo-functors-rebased` (you might need to re-modify `ply_parser.h`) ?

**Comment by zhouchuangchuang** [comment]
Hey,
My computer is win10, and I use VS2017, what's more, the version of Boost is 1.68, and Cmake is 3.12.
(Now I have added the path of super4pcs_algo.lib in Linker--Input--Additional Dependencies like D:\Program Files (x86)\Super4PCS-v1.1.3-win64\lib\super4pcs_algo.lib, but I can't find the path of super4pcs_utils.lib)
My freind uses LINUX, and he told me that the programm in his computer can run without problem.

**Comment by nmellado** [comment]
Did you try to clean the cmake cache ?
This should be fixed with `algo-functors-rebased`.

**Comment by zhouchuangchuang** [comment]
Hi,
I have cleaned the cmake cache. Und This time I have used the branch algo-functors-rebased. Then there was the problem like first----- Error C2248 'pcl::io::ply::ply_parser::scalar_property_definition_callbacks_type::callbacks_element': cannot access private struct declared in class 'pcl::io::ply::ply_parser::scalar_property_definition_callbacks_type' .

So I corrected the private to public.  After this step, amazing!!! There are four warning...
1.   Severity	Code	Description	Project	File	Line	Suppression State
Error	C2923	'gr::FunctorSuper4PCS': 'AdaptivePointFilter' is not a valid template type argument for parameter 'PointFilterFunctor'	OpenGR-PCLWrapper	C:\Users\Desktop\OpenGR-algo-functors-rebased\demos\PCLWrapper\pcl\registration\impl\super4pcs.hpp	83	
2.   Severity	Code	Description	Project	File	Line	Suppression State
Error	C3203	'FunctorSuper4PCS': unspecialized class template can't be used as a template argument for template parameter 'Functor', expected a real type	OpenGR-PCLWrapper	C:\Users\Desktop\OpenGR-algo-functors-rebased\demos\PCLWrapper\pcl\registration\impl\super4pcs.hpp	83	
3.  Severity	Code	Description	Project	File	Line	Suppression State
Error	C2065	'AdaptivePointFilter': undeclared identifier	OpenGR-PCLWrapper	C:\Users\Desktop\OpenGR-algo-functors-rebased\demos\PCLWrapper\pcl\registration\impl\super4pcs.hpp	83	
4.  Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'AdaptivePointFilter': is not a member of 'gr'	OpenGR-PCLWrapper	C:\Users\Desktop\OpenGR-algo-functors-rebased\demos\PCLWrapper\pcl\registration\impl\super4pcs.hpp	83	

So I wanted to try the program of Super4Pcs in Demo, but Cmake told me that: CMake Error at CMakeLists.txt:10 (add_dependencies):
  The dependency target "opengr" of target "Super4PCS" does not exist.


So sorry to disturb you....And Thank you for your reply.

**Comment by zhouchuangchuang** [comment]
And after I built the solution of Super4PCS, the error is :
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'opengr_utils.lib'	Super4PCS	E:\1.1HIWI\1\3.new branch\OpenGR-algo-functors-rebased\demos\Super4PCS\LINK	1

**Comment by zhouchuangchuang** [comment]
I think the most terrible problem is Error 1104, because I can't find the path of file opengr_utils.lib...May you help me?

**Comment by nmellado** [comment]
I'm currently investing to solve your problem.

Regarding the link error, do you open the project directly using VS2017, or do you generate a solution using cmake and then load it in VS2017 ?

**Comment by zhouchuangchuang** [comment]
Hi,
Thank you for your reply. First I run the programm run-example.bat in scripts. Then  I use your CmakeLists of Demos directly in Cmake, then load .sln in vs2017. Because the header file is #include "gr/../..", so I set the gr folder in properties--C/C++--Additional Include Diretories.

Finally I get the Link error, but I think perhaps there will be other errors, after we solve the LINK error.

Thank you.

**Comment by nmellado** [comment]
I see, I've not tested to directly load the PCLWrapper CMakelist.

As described [here](https://storm-irit.github.io/OpenGR/a00008.html)**, you need to load OpenGR CMakelist.txt with VS, and then compile the PCLWrapper by building the target `OpenGR-PCLWrapper`.

** There is a typo in the online documentation, read `OpenGR-PCLWrapper` and not `Super4PCS-PCLWrapper`.

**Comment by nmellado** [comment]
No worries. But please carefully read the documentation. If something is not clear, I can update it.

As described in the [compilation instructions](https://storm-irit.github.io/OpenGR/a00002.html), you can load cmake projects in Visual Studio using the so called [cmake plugin](https://blogs.msdn.microsoft.com/vcblog/2016/10/05/cmake-support-in-visual-studio/).

With this plugin installed, just open the folder containing the CMakefile.txt at the root of the directory ([this one](https://github.com/STORM-IRIT/OpenGR/blob/master/CMakeLists.txt)), and build the PCLWrapper target (dependencies will be compiled if needed).

**Comment by zhouchuangchuang** [comment]
Hi，
Please don't close this Issue..I mean, I haven't solved the problem. Now I am dealing with problem of vs for hours:
1> Access to the path 'C:\Users\__\CMakeBuilds\53926e5a-74fe-4933-98dd-1b27eaf43917\build\x64-Debug' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at libcmake.CMakeDaemonDriver.Initialize(CMakeLists parent, String cmakeDaemonDirectory, String cmakeListsDirectory, String buildOutputDirectory, Dictionary`2 variables, CancellationToken cancel)
   at libcmake.CMakeDaemonDriver..ctor(String cmakeDaemonDirectory, String cmakeListsDirectory, String cmakeGeneratorName, String cmakeConfigName, String cmakeBuildConfigType, String cmakeCommandLine, String buildOutputDirectory, String inheritEnvironments, Dictionary`2 variables, CancellationToken cancel, CMakeLists parent)
   at libcmake.CMakeLists.<ParseWithoutCacheAsync>d__112.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.CMake.Project.CMakeListsUtils.<ParseAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.CMake.Project.CMakeListsCache.<ParseAsyncImpl>d__29.MoveNext()

After I solve this question, I will tell you.

Thank you for your reply again.

**Comment by zhouchuangchuang** [comment]
Hi,
Sorry, but I must ask you a question, which version of Boost do you use, because after I open OPENGR-Folder, there are always errors like:
 Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at D:/Program Files/C/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.11/Modules/FindBoost.cmake:2044 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.		D:/Program Files/C/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.11/Modules/FindBoost.cmake	2044	

And my version is 1.68.

**Comment by zhouchuangchuang** [comment]
Hi.
I solve the Boost problem by rebuild boost:    b2 variant=release link=static runtime-link=static stag

**Comment by nmellado** [comment]
I got a notification telling me you solved your problem, but can't find the post.
Is it good now ?

Note that, as written in cmake error message, you need to tell cmake where is boost. 
To do so, you need to edit the options passed to cmake and specify `BOOST_ROOT` to the directory containing boost. 
See how to set cmake parameters in VS2017: https://docs.microsoft.com/fr-fr/cpp/ide/cmake-tools-for-visual-cpp#cmake_settings

**Comment by zhouchuangchuang** [comment]
Today I find the solution of the Boost-problem, when I installed boost library, I just input bootstrap.bat and b2 in cmd.   But the right step after bootstrap.bat is b2 --toolset=msvc-14.1 --build-type=complete stage
(for vs2017 is 14.1)

**Comment by zhouchuangchuang** [comment]
I forgot to say that, we should also to add 
set(BOOST_ROOT "D:/Program Files (x86)/boost_1_68_0")
in CMakeLists.txt in src--gr/super4pcs---io.

**Comment by zhouchuangchuang** [comment]
Now I have met a now problem...
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2440	'initializing': cannot convert from 'std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>>' to 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'	D:\Program Files\C\Common7\IDE\CMakeLists.txt	C:\Users\zh\Desktop\OpenGR-master\src\super4pcs\io\io.cc	154

**Comment by zhouchuangchuang** [comment]
Hi，
First, thank you for your share. And I have solved the problem of PCL Wrapper. I used the programm in your [Super4PCS](https://github.com/nmellado/Super4PCS), and it works very good. 

But the programm in OpenGR doesn't work,the problem is C2440. Next week I will share the experience about PCL Wrapper. I have maken so many foolish problems.

Thank you for your reply and help.
