### ISSUE TITLE
/bigobj

### ISSUE THREAD

**Issue by afabri** [STORM-IRIT/OpenGR#122]
When building the solution in VC 2022 I get error messages 

````
C:\GitHub\OpenGR\apps\Super4PCS\super4pcs_test.cc : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj [C:\GitHub\OpenGR\VC\apps\Super4PCS\Super4PCS.vcxproj]
````

**Comment by nmellado** [comment]
Hi,
Is #123 fixing the problem on your side ?

**Comment by afabri** [comment]
That fixes it.  But  there is the same error for matching, pair_extraction, and ExtPointBinding
