### ISSUE TITLE
Could not align well - teeths

### ISSUE THREAD

**Issue by nmellado** [STORM-IRIT/OpenGR#18]
This is a copy of the issue https://github.com/nmellado/Super4PCS/issues/65:

> I could not get proper alignment with the attached clouds.
> I have tried so many parameters but no luck.
> Can you pls advice some parameter or way of thinking to align at least these two.
> 
> My current parameters are
> overlap: 0.6
> delta: 5.0
> n_points: 150
> max_time_seconds: 30
> 
> [CloudsObj.zip](https://github.com/nmellado/Super4PCS/files/2739978/CloudsObj.zip)

**Comment by nmellado** [comment]
I managed to align this dataset using the following parameters:
```bash
./Super4PCS -i cloudref.ply cloudalign.ply -o 0.9 -d 5.0 -n 500
``` 
You need a high overlap as these models are mostly covering the same shape.
![screenshot from 2019-01-09 10-40-06](https://user-images.githubusercontent.com/6310221/50890800-347f7c80-13fb-11e9-9702-3b58b6cd6c7d.png)

**Comment by meakcey** [comment]
If the picture you attached is alignment result, it is not aligned, that is the initial positions already.
You can see from the front teeth not fits.

**Comment by meakcey** [comment]
I am aligning them with CloudCompare and results 
![well aligned](https://user-images.githubusercontent.com/5054547/50892221-0b68e700-140f-11e9-82ce-99a29c070774.JPG)

**Comment by nmellado** [comment]
What you are showing is a result of a fine registration algorithm, like ICP.
The purpose of Super4PCS is to fine a rough alignment, to be refined using ICP.
