### ISSUE TITLE
Could not compile - VS2015

### ISSUE THREAD

**Issue by meakcey** [STORM-IRIT/OpenGR#19]
Having some build errors like below
Could not figure that out.

CMake Result
Selecting Windows SDK version 10.0.16299.0 to target Windows 10.0.17134.
Eigen3 root path: C:/Program Files/Eigen
STB root path: C:/Program Files/OpenGR/3rdparty/stb
CMake Warning (dev) at src/gr/io/CMakeLists.txt:11 (find_package):
  Policy CMP0074 is not set: find_package uses PackageName_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable Boost_ROOT is set to:

    C:\Program Files\boost\boost_1_67_0\lib64-msvc-14.0

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

Boost version: 1.67.0
Found the following Boost libraries:
  system
  filesystem
[Deps] Use Boost 106700 for image loading
CMake Warning (dev) at tests/CMakeLists.txt:98 (find_package):
  Policy CMP0074 is not set: find_package uses PackageName_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable Boost_ROOT is set to:

    C:\Program Files\boost\boost_1_67_0\lib64-msvc-14.0

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at demos/MeshlabPlugin/CMakeLists.txt:36 (message):
  Skipping Meshlab plugin preparation - Meshlab not found

CMake Warning (dev) at demos/PCLWrapper/CMakeLists.txt:3 (find_package):
  Policy CMP0074 is not set: find_package uses PackageName_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable PCL_ROOT is set to:

    C:\PCL

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/PCL/cmake/PCLConfig.cmake:133 (find_package):
  Policy CMP0074 is not set: find_package uses PackageName_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable Boost_ROOT is set to:

    C:\Program Files\boost\boost_1_67_0\lib64-msvc-14.0

  For compatibility, CMake is ignoring the variable.
Call Stack (most recent call first):
  C:/PCL/cmake/PCLConfig.cmake:643 (find_boost)
  C:/PCL/cmake/PCLConfig.cmake:865 (find_external_library)
  demos/PCLWrapper/CMakeLists.txt:3 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

Could NOT find openni (missing: OPENNI_LIBRARY OPENNI_INCLUDE_DIRS) 
Could NOT find openni (missing: OPENNI_LIBRARY OPENNI_INCLUDE_DIRS) 
[Demos] PCL found, creating target PCLWrapper
[download 75% complete]
[download 100% complete]
[download 44% complete]
[download 70% complete]
[download 100% complete]
Configuring done
Generating done

Visual Studio Release mode ALL_BUILD errors
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2244	'gr::CongruentSetExplorationBase<_Traits,_TransformVisitor,_PairFilteringFunctor,OptExts...>::ComputeTransformation': unable to match function definition to an existing declaration	PCLWrapper	c:\program files\opengr\src\gr\algorithms\congruentSetExplorationBase.hpp	111	
Error	C2027	use of undefined type 'gr::Utils::crtp::make_base<Derived>'	Super4PCS	C:\Program Files\OpenGR\src\gr\utils\crtp.h	46	
Error	C2027	use of undefined type 'gr::Utils::crtp::make_base<Derived>'	PCLWrapper	C:\Program Files\OpenGR\src\gr\utils\crtp.h	46	
Error	C2146	syntax error: missing '>' before identifier 'type'	Super4PCS	C:\Program Files\OpenGR\src\gr\utils\crtp.h	46	
Error	C2146	syntax error: missing '>' before identifier 'type'	PCLWrapper	C:\Program Files\OpenGR\src\gr\utils\crtp.h	46	
Error	C2516	'TBase': is not a legal base class	Super4PCS	C:\Program Files\OpenGR\src\gr\algorithms\matchBase.h	85	
Error	C2516	'TBase': is not a legal base class	PCLWrapper	C:\Program Files\OpenGR\src\gr\algorithms\matchBase.h	85	
Error	C2440	'initializing': cannot convert from 'std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>>' to 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'	opengr_io	C:\Program Files\OpenGR\src\gr\io\io.cc	154	
Error	C2244	'gr::CongruentSetExplorationBase<_Traits,_TransformVisitor,_PairFilteringFunctor,OptExts...>::Verify': unable to match function definition to an existing declaration	Super4PCS	c:\program files\opengr\src\gr\algorithms\congruentSetExplorationBase.hpp	444	
Error	C2244	'gr::CongruentSetExplorationBase<_Traits,_TransformVisitor,_PairFilteringFunctor,OptExts...>::Verify': unable to match function definition to an existing declaration	PCLWrapper	c:\program files\opengr\src\gr\algorithms\congruentSetExplorationBase.hpp	444	
Error	C2244	'gr::CongruentSetExplorationBase<_Traits,_TransformVisitor,_PairFilteringFunctor,OptExts...>::Perform_N_steps': unable to match function definition to an existing declaration	Super4PCS	c:\program files\opengr\src\gr\algorithms\congruentSetExplorationBase.hpp	178	
Error	C2244	'gr::CongruentSetExplorationBase<_Traits,_TransformVisitor,_PairFilteringFunctor,OptExts...>::Perform_N_steps': unable to match function definition to an existing declaration	PCLWrapper	c:\program files\opengr\src\gr\algorithms\congruentSetExplorationBase.hpp	178	
Error	C2244	'gr::CongruentSetExplorationBase<_Traits,_TransformVisitor,_PairFilteringFunctor,OptExts...>::ComputeTransformation': unable to match function definition to an existing declaration	Super4PCS	c:\program files\opengr\src\gr\algorithms\congruentSetExplorationBase.hpp	111

**Comment by nmellado** [comment]
What's your version of Visual Studio ?

**Comment by meakcey** [comment]
VS2015

**Comment by nmellado** [comment]
We recommend VS2017 (see documentation: https://storm-irit.github.io/OpenGR/a00002.html)

**Comment by meakcey** [comment]
So it is better to work with Super4PCS for now =)
Thanks

**Comment by nmellado** [comment]
ok.

**Comment by hejinying** [comment]
@meakcey hi, have you already solve this problems? I met the same problem when compile with VS2015.  please tell me how to solve if you already succeed. thanks!

**Comment by meakcey** [comment]
unfortunately I could not compile with VS2015 so I returned back to Super4CS

**Comment by hejinying** [comment]
@meakcey got  it! thanks all the way!
