### ISSUE TITLE
Running the pcl wrapper on the hippo set, does not align

### ISSUE THREAD

**Issue by antithing** [STORM-IRIT/OpenGR#20]
Hi, and thank you for making this code available.
I am trying to run the PCL wrapper on the hippo dataset, with the command:

```
.\OpenGR-PCLWrapper.exe  .\hippo1.obj  .\hippo2.obj  -d 0.01    -o 0.7  -t 1000 -n 200  -r aligned.ply
```

It runs fine, but in the visualizer, does not align, printing:

```
> Loading point clouds...
Failed to find match for field 'curvature'.
Failed to find match for field 'curvature'.
> Starting alignment...
norm_max_dist: 5
Initial LCP: 1
> Final score: 300392.750000
Alignment took 9ms.

    |  1.000  0.000  0.000 |
R = |  0.000  1.000  0.000 |
    |  0.000  0.000  1.000 |

t = < 0.000, 0.000, 0.000 >

```
Do I just have the params wrong? or am i missing something?

Thanks!

**Comment by nmellado** [comment]
Thanks for the report.
Indeed, the CLI options weren't transmitted to the matcher, so this behavior.

This is fixed by #21, will be merged after the continuous integration tests succeed.

**Comment by nmellado** [comment]
Changes have been merged, thanks,

**Comment by nmellado** [comment]
@Shubodh I can see in your log that the value `0.01` set for delta in CLI is not used by the wrapper (`Initial LCP: 1`).
This what was happening before the fix.

Please check you really get the latest commit and recompiled everything.

**Comment by nmellado** [comment]
This issue should be fixed now, please reopen if not.
