### ISSUE TITLE
error to install meshlabplugin

### ISSUE THREAD

**Issue by QiuYilin** [STORM-IRIT/OpenGR#27]
I followed the tutorial and met a bug that I can not fix.
I ran 

> make Meshlab_install_plugin

and it showed

> Error copying directory from "/lib/" to "/home/qiuyilin/meshlab/src/external/lib/linux-g++".

but   copying directory from "/include/" to "/home/qiuyilin/meshlab/src/external/Inc/linux-g++" can pass successfully

the directory /home/qiuyilin/OpenGR/build/install/lib has a cmake folder and libopengr_io.a

**Comment by nmellado** [comment]
Dear @QiuYilin ,
Could you please post here the full trace when running cmake from scratch ?

**Comment by nmellado** [comment]
OpenGR is now embedded in Meshlab since release 2020.07: https://github.com/cnr-isti-vclab/meshlab/releases/tag/Meshlab-2020.07, and built-in meshlab plugin is not supported anymore.
