### ISSUE TITLE
How to use super4pcs in ROS ?

### ISSUE THREAD

**Issue by QiuYilin** [STORM-IRIT/OpenGR#28]
I have compiled the source code and modify the cmakelist of the package like this:
```
cmake_minimum_required(VERSION 2.8.3)
project(cood_tran)

## Compile as C++11, supported in ROS Kinetic and newer
add_compile_options(-std=c++11)
find_package(catkin REQUIRED COMPONENTS darknet_ros_msgs roscpp sensor_msgs image_transport std_msgs pcl_ros cood_tran_msgs cv_bridge)

find_package(OpenCV REQUIRED)
find_package(Super4PCS REQUIRED)
find_package( Eigen3 REQUIRED )

catkin_package()
include_directories(
  ${catkin_INCLUDE_DIRS}
  ${OpenCV_INCLUDE_DIRS}
  ${Super4PCS_INCLUDE_DIR}
)


include_directories(
  include ${catkin_INCLUDE_DIRS}
# include
  ${catkin_INCLUDE_DIRS}
  ${OpenCV_LIBRARIES}
  ${EIGEN3_INCLUDE_DIR}
)




add_executable(cood_tran_node
  src/cood_tran_node.cpp src/cood_tran.cpp
)
add_executable(opengr
  src/opengr.cpp
)


add_dependencies(cood_tran_node  ${${PROJECT_NAME}_EXPORTED_TARGETS} ${catkin_EXPORTED_TARGETS})
add_dependencies(opengr  ${${PROJECT_NAME}_EXPORTED_TARGETS} ${catkin_EXPORTED_TARGETS})

target_link_libraries(cood_tran_node 
  ${catkin_LIBRARIES}
)

target_link_libraries(opengr
  ${catkin_LIBRARIES}
  ${Super4PCS_LiBRARIES}
)




# add_executable(cood_tran_depth src/cood_tran_depth.cpp)
#  target_link_libraries(cood_tran_depth
#    ${catkin_LIBRARIES}
#    ${OpenCV_LIBRARIES}
#  )
# add_dependencies(cood_tran_depth ${${PROJECT_NAME}_EXPORTED_TARGETS} ${catkin_EXPORTED_TARGETS})
# target_link_libraries(cood_tran_depth
#   ${catkin_LIBRARIES}
# )



SET(CMAKE_BUILD_TYPE "Debug")  
SET(CMAKE_CXX_FLAGS_DEBUG "$ENV{CXXFLAGS} -O0 -Wall -g -ggdb")
SET(CMAKE_CXX_FLAGS_RELEASE "$ENV{CXXFLAGS} -O3 -Wall")
```
but it shows

> Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
> CMake Error at Huskybot_arm/cood_tran/cood_tran/CMakeLists.txt:9 (find_package):
>   By not providing "FindSuper4PCS.cmake" in CMAKE_MODULE_PATH this project
>   has asked CMake to find a package configuration file provided by
>   "Super4PCS", but CMake did not find one.
> 
>   Could not find a package configuration file provided by "Super4PCS" with
>   any of the following names:
> 
>     Super4PCSConfig.cmake
>     super4pcs-config.cmake
> 
>   Add the installation prefix of "Super4PCS" to CMAKE_PREFIX_PATH or set
>   "Super4PCS_DIR" to a directory containing one of the above files.  If
>   "Super4PCS" provides a separate development package or SDK, be sure it has
>   been installed.

**Comment by nmellado** [comment]
As visible here: https://github.com/STORM-IRIT/OpenGR/blob/master/cmake/Config.cmake.in
the package name is `OpenGR`, not `Super4PCS`.

**Comment by nmellado** [comment]
As mentioned in #63 , OpenGR can be used in ROS.
Please re-open this issue if you problem is not solved.
