### ISSUE TITLE
Super4PCS always output identity matrix for two distant point cloud

### ISSUE THREAD

**Issue by tyronedong** [STORM-IRIT/OpenGR#29]
I want to apply Supper4PCS to two point cloud, but the program always output identity matrix. I tried different parameters but the result didn't change.
Could you please check my point clouds and tell me how to register them? Thanks a lot!
ps: I use pre-compiled Super4PCS.exe(download from nmellado/Super4PCS/Super4PCS-v1.1.3-win64)
the command line I use is ".\Super4PCS.exe -i .\6\object0.ply
 .\6\object1.ply -o 0.9"

[two-point-cloud.zip](https://github.com/STORM-IRIT/OpenGR/files/3240671/two-point-cloud.zip)

**Comment by LAICHAO2018** [comment]
这个问题解决了吗，朋友，我也遇到这样的问题了，请教~

**Comment by nmellado** [comment]
For the record, these files seems to be not fully compatible with the library IO embedded in the Super4PCS app. I had to load and save them with Meshlab to process them.

Alternatively, you can also use the OpenGR-PCLWrapper to register your files directly
![image](https://user-images.githubusercontent.com/6310221/89873577-f17b2180-dbba-11ea-9906-e79481af686a.png)
