### ISSUE TITLE
Unable to compile using the commands in documentation[linux]

### ISSUE THREAD

**Issue by Andreachen0707** [STORM-IRIT/OpenGR#30]
Hi,
I tried to compile the project to use the demos, however, I encounter some weird errors:

[ 33%] Built target opengr_io
Scanning dependencies of target opengr
[ 33%] Built target opengr
[ 50%] Building CXX object demos/Super4PCS/CMakeFiles/Super4PCS.dir/super4pcs_test.cc.o
In file included from /home/OpenGR/src/gr/algorithms/congruentSetExplorationBase.h:54:0,
                 from /home/OpenGR/src/gr/algorithms/match4pcsBase.h:18,
                 from /home/OpenGR/demos/Super4PCS/super4pcs_test.cc:4:
/home/OpenGR/src/gr/algorithms/matchBase.h:73:46: error: expected 'class' before '...' token
           template < class, class > typename ... OptExts >
                                              ^
In file included from /home/OpenGR/src/gr/algorithms/matchBase.h:242:0,
                 from /home/OpenGR/src/gr/algorithms/congruentSetExplorationBase.h:54,
                 from /home/OpenGR/src/gr/algorithms/match4pcsBase.h:18,
                 from /home/OpenGR/demos/Super4PCS/super4pcs_test.cc:4:
/home/OpenGR/src/gr/algorithms/matchBase.hpp:29:73: error: expected 'class' before '...' token
 template <typename TransformVisitor, template < class, class > typename ... OptExts>
                                                                         ^
/home/OpenGR/src/gr/algorithms/matchBase.hpp:40:73: error: expected 'class' before '...' token
 template <typename TransformVisitor, template < class, class > typename ... OptExts>
                                                                         ^
/home/OpenGR/src/gr/algorithms/matchBase.hpp:44:73: error: expected 'class' before '...' token
 template <typename TransformVisitor, template < class, class > typename ... OptExts>
                                                                         ^
/home/OpenGR/src/gr/algorithms/matchBase.hpp:70:73: error: expected 'class' before '...' token
 template <typename TransformVisitor, template < class, class > typename ... OptExts>
                                                                         ^
/home/OpenGR/src/gr/algorithms/matchBase.hpp:107:73: error: expected 'class' before '...' token
 template <typename TransformVisitor, template < class, class > typename ... OptExts>
                                                                         ^
/home/OpenGR/src/gr/algorithms/matchBase.hpp:122:73: error: expected 'class' before '...' token
 template <typename TransformVisitor, template < class, class > typename ... OptExts>
                                                                         ^
/home/OpenGR/src/gr/algorithms/matchBase.hpp:260:73: error: expected 'class' before '...' token
 template <typename TransformVisitor, template < class, class > typename ... OptExts>
                                                                         ^
In file included from /home/OpenGR/src/gr/algorithms/congruentSetExplorationBase.h:208:0,
                 from /home/OpenGR/src/gr/algorithms/match4pcsBase.h:18,
                 from /home/OpenGR/demos/Super4PCS/super4pcs_test.cc:4:
/home/OpenGR/src/gr/algorithms/congruentSetExplorationBase.hpp:28:46: error: expected 'class' before '...' token
           template < class, class > typename ... OptExts >
                                              ^
Seems like I cannot compile the standalone, any hint on where I did wrong? I just follow the instruction on the website, set everything as default.

Many thanks in advance on any suggestion!

Best,
Andrea

**Comment by nmellado** [comment]
Dear @Andreachen0707 , 
thanks for your report,
Could you please post here your compiler version ?

**Comment by Andreachen0707** [comment]
Hi Nicolas,
Thank you for your reply!
I put the compiler version below:

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.9.2-10+deb8u2' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --with-arch-32=i586 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.2 (Debian 4.9.2-10+deb8u2) 

And interestingly, I can compile the repo in the other link, which I believe is the original one (no longer maintained).

Best,
Andrea

**Comment by nmellado** [comment]
Dear @Andreachen0707 
Sorry for the delay to process this, but your issue should now be fixed.
