### ISSUE TITLE
Where is demo

### ISSUE THREAD

**Issue by getupgetup** [STORM-IRIT/OpenGR#35]
Hi, I want use the super4pcs in my own program but I don't know how to do that. Is there any demo to teach me how to use Super4PCS class and set the parameters? Thank you!

**Comment by nmellado** [comment]
Hi,
It is all in the documentation: 
 - how to use the library in your own software: https://storm-irit.github.io/OpenGR/a00002.html#usage
 - example mixing PCL and OpenGR: https://storm-irit.github.io/OpenGR/a00005.html
 - Super4PCS parameter description: https://storm-irit.github.io/OpenGR/a00012.html

**Comment by getupgetup** [comment]
Thanks~
