### ISSUE TITLE
git submodule on Windows

### ISSUE THREAD

**Issue by afabri** [STORM-IRIT/OpenGR#38]
Is there a known problem with cmake failing to get stb as a submodule?  In cmake-gui I get:
error: 
pathspec 'C:/3rdPartyLibs/OpenGR/3rdparty/stb' did not match any file(s) known to git.

**Comment by nmellado** [comment]
As far as I see, https://github.com/nothings/stb is still online.
The submodule is supposed to be automatically fetched the first time you run cmake:
https://github.com/STORM-IRIT/OpenGR/blob/master/CMakeLists.txt#L115-L122

Can you post here the path you get from this line (https://github.com/STORM-IRIT/OpenGR/blob/master/CMakeLists.txt#L124)
```cmake
message(STATUS "STB root path: ${STB_INCLUDE_DIR}")
```
