### ISSUE TITLE
Scale between 3d CAD model and scene

### ISSUE THREAD

**Issue by ghost** [STORM-IRIT/OpenGR#41]
Hello!

Thank you for great job!

I would like to use OpenGR to estimate the position ad orientation. However, there is some scaling between 3D CAD model and scene (object of interest from depth image). Both are converted to point cloud and saved as .ply files.

What would you suggest to do in my case? Thank you.

**Comment by nmellado** [comment]
Hi @AkmaralMoldagalieva ,
You can try to turn on the preprocessor variable `MULTISCALE`, which enable scale estimation.
But, be warned that this feature slows down the exploration a lot.
Also, this feature is very experimental (and thus not documented), and has not been tested extensively, and not recently.

**Comment by x1597275** [comment]
> Hi @AkmaralMoldagalieva ,
> You can try to turn on the preprocessor variable `MULTISCALE`, which enable scale estimation.
> But, be warned that this feature slows down the exploration a lot.
> Also, this feature is very experimental (and thus not documented), and has not been tested extensively, and not recently.

please tell me how to turn on the variable MULTI SCALE. Thank you!

**Comment by AkmaralMoldagalieva** [comment]
Hi! Sorry for my late response. I couldn't solve the problem with scaling  and end up using libpointmatcher library for pose estimation.

**Comment by nmellado** [comment]
Ok no problem.
Libpointermatcher is well adapted if you have an initial guess on the position.
Cheers
