### ISSUE TITLE
Match4PCSBase::TryCongruentSet issue

### ISSUE THREAD

**Issue by easterngarden** [STORM-IRIT/OpenGR#42]
I managed to make opengr global registration plugin in meshlab works. However, when I ran example hippo1 and hippo2 with global registration plugin with default setting, it hangs up forever. By debugging, I found that the following condition in TryCongruentSet cannot be satisfied since best_LCP cannot be greater than 1.0 and options_.getTerminateThreshold() returns 1 by default.
          // Terminate if we have the desired LCP already.
          if (best_LCP_ > options_.getTerminateThreshold()){
            continue;
          }
I am kind of confused by the comment since it seems indicate to exit the loop or so. If I change the codes as shown below, I got result as shown in attach file.
          if (best_LCP_ >= options_.getTerminateThreshold()){
            return true;
          }

Please advise this issue.

![image](https://user-images.githubusercontent.com/36804327/67233772-baa00900-f3f8-11e9-904d-51990745258b.png)

**Comment by nmellado** [comment]
Thanks for the report.
Meshlab plugin is deprecated and will be removed in the next version.
