### ISSUE TITLE
Align two 2D point cloud, I set the value z=0 for all points, the rotation of result is identity matrix?

### ISSUE THREAD

**Issue by lfy89** [STORM-IRIT/OpenGR#43]
Does this code support 2D point cloud? I want to align 2D map,  and I set all points' z=0, the result is strange:
      1        0        0 -7.66553
       0        1        0 -17.0312
       0        0        1        0
       0        0        0        1
I test many parameters, the rotation matrix always identity matrix , I don't know ho to solve it, please help, thank you!

**Comment by nmellado** [comment]
Hi @lfy89 ,
I've not tested such scenario, however I see no reason why this should not work.

Usually, getting an identity matrix means that the algorithm parameters are not properly set. 
Did you follow the recommendation found here: https://storm-irit.github.io/OpenGR/a00012.html

**Comment by nmellado** [comment]
Any update on this ?
