### ISSUE TITLE
problem with number_of_trials_ computation!! 

### ISSUE THREAD

**Issue by amirhosseingholami** [STORM-IRIT/OpenGR#45]
When I try to register different point clouds, I usually get incorrect registration! 
please check this line of code! because the 
https://github.com/STORM-IRIT/OpenGR/blob/ad80cacbdb5cc9bf034e9a9613f1982105e6708d/src/gr/algorithms/congruentSetExplorationBase.hpp#L89
because the program always gets inside this if statement! and the number_of_trials_ always equals kMinNumberOfTrials!!
I think there is a problem with computation of number_of_trials_ !!

**Comment by nmellado** [comment]
Hi,
This might be caused by improper parameter setting.
Did you follow the instructions given in the documentation ? 
https://storm-irit.github.io/OpenGR/a00012.html

**Comment by amirhosseingholami** [comment]
yes, the parameters are set! it even happens on your scripts/run-example.sh example!!

**Comment by nmellado** [comment]
> yes, the parameters are set! it even happens on your scripts/run-example.sh example!! check the results of Super4PCS with hippo1.obj & hippo2.obj
You mean that running the script provided as example does not work ?
This is surprising I cannot reproduce this error, could you post the output of the command line in your post so I can understand what is going on ?

> the 4PCS with hippo1.obj & hippo2.obj is ok with "kMinNumberOfTrials=4" but if you try other datasets, you will get wrong results.
Parameter setting needs to be adapted to each dataset. Could you share a concrete use case ?, e.g., input models and parameter used.

**Comment by amirhosseingholami** [comment]
> > yes, the parameters are set! it even happens on your scripts/run-example.sh example!! check the results of Super4PCS with hippo1.obj & hippo2.obj
> 
> You mean that running the script provided as example does not work ?
> This is surprising I cannot reproduce this error, could you post the output of the command line in your post so I can understand what is going on ?
> 
> > the 4PCS with hippo1.obj & hippo2.obj is ok with "kMinNumberOfTrials=4" but if you try other datasets, you will get wrong results.
> 
> Parameter setting needs to be adapted to each dataset. Could you share a concrete use case ?, e.g., input models and parameter used.

Here is the example.sh results:

```bash
Last login: Thu Feb 27 21:20:17 on console
amirhosseingholami@Amirhosseins-MacBook-Pro ~ % cd /usr/local/myfiles/OpenGR/build/install/scripts 
amirhosseingholami@Amirhosseins-MacBook-Pro scripts % ./run-example.sh         
zsh: permission denied: ./run-example.sh
amirhosseingholami@Amirhosseins-MacBook-Pro scripts % sudo ./run-example.sh
sudo: setrlimit(8): Invalid argument
Password:
------------------------------
Running Super4PCS
Starting registration
norm_max_dist: 0.01
Initial LCP: 0.005
sq_max_base_diameter_: 0.334532          
sq_max_base_diameter_: 0.334532          
sq_max_base_diameter_: 0.334532           
sq_max_base_diameter_: 0.334532           
Score: 0.285st: 0.285000                  
(Homogeneous) Transformation from ../assets/hippo2.obj to ../assets/hippo1.obj: 
  0.766565  -0.181565  -0.615965  -0.136909
  0.187139   0.980725 -0.0561896 -0.0414001
  0.614294 -0.0721984   0.785767 -0.0480413
         0          0          0          1
Exporting Matrix to mat_super4pcs_fast.txt...
Export DONE
Exporting Registered geometry to super4pcs_fast.obj...
Export DONE
real 0.70
user 0.40
sys 0.27
------------------------------
Running 4PCS
Starting registration
norm_max_dist: 0.01
Initial LCP: 0.005
sq_max_base_diameter_: 0.334532          
sq_max_base_diameter_: 0.334532          
sq_max_base_diameter_: 0.334532           
sq_max_base_diameter_: 0.334532           
Score: 0.815st: 0.815000                  
(Homogeneous) Transformation from ../assets/hippo2.obj to ../assets/hippo1.obj: 
   0.742057   0.0310279   -0.669618   -0.101101
 -0.0555907    0.998336  -0.0153448 -0.00393251
   0.668028   0.0486113    0.742547  -0.0323997
          0           0           0           1
Exporting Matrix to mat_4pcs_fast.txt...
Export DONE
Exporting Registered geometry to 4pcs_fast.obj...
Export DONE
real 1.91
user 1.50
sys 0.34
------------------------------
Running PCLWrapper
> Loading point clouds...
Failed to find match for field 'curvature'.
Failed to find match for field 'curvature'.
> Starting alignment...
norm_max_dist: 0.01
Initial LCP: 0.005
sq_max_base_diameter_: 0.334532          
sq_max_base_diameter_: 0.334532          
sq_max_base_diameter_: 0.334532           
sq_max_base_diameter_: 0.334532           
> Final score: 0.0000000                  
Alignment took 122ms.

    |  0.767 -0.182 -0.616 | 
R = |  0.187  0.981 -0.056 | 
    |  0.614 -0.072  0.786 | 

t = < -0.137, -0.041, -0.048 >

```

and here the screenshot
<img width="1280" alt="Screen Shot 2020-02-27 at 9 32 56 PM" src="https://user-images.githubusercontent.com/9483000/75472984-9efdce00-59a9-11ea-9230-92a526adacee.png">


as you see 2 point clouds did not registered! 
I tested the code in Xcode in debug mode, I just run the program line by line and step by step many times and found that problem! 
it does not matter what is your delta or overlap parameter, it's always goes into the mentioned if statement and "kMinNumberOfTrials=4"!!!

**Comment by nmellado** [comment]
Dear @amirhosseingholami ,

I tested again and cannot reproduce this bug, see my trace below.
I am on ubuntu 18.04, compilation with gcc 7.5.0, chealpix disabled.

 
```bash
$ ./run-example.sh 
------------------------------
Running Super4PCS
Starting registration
norm_max_dist: 0.01
Initial LCP: 0.015
sq_max_base_diameter_: 0.503668          
sq_max_base_diameter_: 0.503668          
sq_max_base_diameter_: 0.503668           
sq_max_base_diameter_: 0.503668           
Score: 0.56est: 0.560000                  
(Homogeneous) Transformation from ../assets/hippo2.obj to ../assets/hippo1.obj: 
   0.771311   0.0186835   -0.636184   -0.104647
-0.00241791    0.999648   0.0264263  0.00233582
   0.636453  -0.0188447    0.771085  -0.0235855
          0           0           0           1
Exporting Matrix to mat_super4pcs_fast.txt...
Export DONE
Exporting Registered geometry to super4pcs_fast.obj...
Export DONE
real 0.41
user 0.29
sys 0.11
------------------------------
Running 4PCS
Starting registration
norm_max_dist: 0.01
Initial LCP: 0.015
sq_max_base_diameter_: 0.503668          
sq_max_base_diameter_: 0.503668          
sq_max_base_diameter_: 0.503668           
sq_max_base_diameter_: 0.503668           
Score: 0.56est: 0.560000                  
(Homogeneous) Transformation from ../assets/hippo2.obj to ../assets/hippo1.obj: 
   0.771311   0.0186835   -0.636184   -0.104647
-0.00241791    0.999648   0.0264263  0.00233582
   0.636453  -0.0188447    0.771085  -0.0235855
          0           0           0           1
Exporting Matrix to mat_4pcs_fast.txt...
Export DONE
Exporting Registered geometry to 4pcs_fast.obj...
Export DONE
real 1.07
user 0.98
sys 0.08
```

**Comment by nmellado** [comment]
Stale issue, closing. Please re-open if still up to date.
