### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [STORM-IRIT/OpenGR#47]
I would like to point out that identifiers like “[`_OPENGR_ACCELERATORS_KDTREE_H`](https://github.com/STORM-IRIT/OpenGR/blob/f5032fca40dca70da0f6b9895d68c295b09153b7/src/gr/accelerators/kdtree.h#L47 "Update candidate")” and “[`_PCS_UTILS_H_`](https://github.com/STORM-IRIT/OpenGR/blob/a08ef2bc40e93dd4ba2e45cd02521d8a78d28be1/src/gr/sampling.h#L47 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by nmellado** [comment]
Hi @elfring ,

Yes thanks for pointing this, that's true.
I think my preferred option would be to use `#pragma once` everywhere.
I know it is not standard.

**Comment by elfring** [comment]
How do you think about to achieve standard compliance?

**Comment by nmellado** [comment]
Commit 9432643 changes all include guars to `pragma once`.

**Comment by elfring** [comment]
You might know that [this construct is also not standard compliant](https://stackoverflow.com/questions/23696115/is-pragma-once-part-of-the-c11-standard/23699893#answer-23699893 "Is #pragma once part of the C++11 standard?").

**Comment by nmellado** [comment]
Yes I know, but it Is supported by most compilers.
If some users have an issue with this one day, I'll fix it.
