### ISSUE TITLE
make Meshlab_install_plugin

### ISSUE THREAD

**Issue by monage2018** [STORM-IRIT/OpenGR#49]
I want to make the Meshlab Plugin, and i run "git clone https://github.com/cnr-isti-vclab/meshlab.git" in the file  relative to OpenGR is "../". Actually, the cmake find the meshlab src file,but there's no target'Meshlab_install_plugin'.

cmake info:
-- Enable OpenMP
CMake Warning (dev) at cmake/FindMeshlab.cmake:42 (message):
  Automatic plateform detection not ready yet.  Using linux-g++
Call Stack (most recent call first):
  cmake/ConfigureCompiler.cmake:29 (find_package)
  CMakeLists.txt:50 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Meshlab: /home/gaolixu/workspace/SLAM/meshlab/src
-- Enable position independent code
-- Eigen3 root path: /usr/local/include/eigen3
-- STB root path: /home/gaolixu/workspace/SLAM/OpenGR/3rdparty/stb
CMake Warning (dev) at src/gr/utils/CMakeLists.txt:17 (target_sources):
  Policy CMP0076 is not set: target_sources() command converts relative paths
  to absolute.  Run "cmake --help-policy CMP0076" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  An interface source of target "utils" has a relative path.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/gr/accelerators/CMakeLists.txt:32 (target_sources):
  Policy CMP0076 is not set: target_sources() command converts relative paths
  to absolute.  Run "cmake --help-policy CMP0076" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  An interface source of target "accel" has a relative path.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/gr/algorithms/CMakeLists.txt:17 (target_sources):
  Policy CMP0076 is not set: target_sources() command converts relative paths
  to absolute.  Run "cmake --help-policy CMP0076" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  An interface source of target "algo" has a relative path.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- [Deps] Use Boost 105800 for image loading
-- [download 0% complete]
-- [download 22% complete]
-- [download 44% complete]
-- [download 66% complete]
-- [download 88% complete]
-- [download 100% complete]
-- [download 0% complete]
-- [download 13% complete]
-- [download 26% complete]
-- [download 39% complete]
-- [download 52% complete]
-- [download 65% complete]
-- [download 78% complete]
-- [download 91% complete]
-- [download 100% complete]
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gaolixu/workspace/SLAM/OpenGR/build

make Meshlab_install_plugin show
make: *** No rule to make target 'Meshlab_install_plugin'

**Comment by monage2018** [comment]
Sorry, I have found the commit "7f11a48", it says "Remove Meshlab demo as Meshlab is not maintained anymore".

**Comment by nmellado** [comment]
Meshlab project seems to be alive again, so it could make sense to reactivate this demo.
Ideally, a better option would be to add it to meshlab directly, I'll check with them and come back to you.

**Comment by Gaolixu001** [comment]
@nmellado Hi, I've seen your in-depth communication with the Meshlab, Thank you very much for your attention and also for Meshlab cooperation. I am looking forward to yours achievements, Thanks,thanks,thanks.

**Comment by nmellado** [comment]
The plugin has been added to Meshlab master, see https://github.com/cnr-isti-vclab/meshlab/pull/733
