### ISSUE TITLE
how to save the pointcloud after registration and why the pointcloud lose RGB information

### ISSUE THREAD

**Issue by x1597275** [STORM-IRIT/OpenGR#50]
how to save the pointcloud after registration and why the pointcloud lose RGB information

**Comment by nmellado** [comment]
Hi,
Could you indicate which app you use (PCLwrapper or Super4PCS) ?

**Comment by x1597275** [comment]
> Hi,
> Could you indicate which app you use (PCLwrapper or Super4PCS) ?

PCLWrapper

**Comment by nmellado** [comment]
Sorry for the late reply.

The current implementation of the PCL wrapper is a simple demonstrator, illustrating how to use OpenGR in PCL-powered applications.
Nevertheless, PR #50 adds more loaders (obj loader cannot represent vertex colors for point-clouds, only meshes) and automatically saves the registration output as ply.
