### ISSUE TITLE
Linking errors for header only libraries

### ISSUE THREAD

**Issue by jonla1** [STORM-IRIT/OpenGR#58]
Hi,

I noticed that I get a linking error to gr::Utils::OneRingNeighborhood::get. Is there a possiblity that the function can be static or inline to avoid this issue?

Thanks in advance for your feedback.

**Comment by al-tu** [comment]
Hello! I still get linker errors and the proposed solution is to add inline specifiers to template specializations, at the difinition site. Fixed with the linked MR. #69
