### ISSUE TITLE
Compile error when using ROS. Could not find a package configuration file provided by "OpenGR" 

### ISSUE THREAD

**Issue by astronaut71** [STORM-IRIT/OpenGR#63]
Hi I try to use OpenGR with ROS and was following also [https://github.com/STORM-IRIT/OpenGR/issues/28](url) But still got the error
`CMake Error at key_points/CMakeLists.txt:28 (find_package):
  By not providing "FindOpenGR.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenGR", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenGR" with any
  of the following names:

    OpenGRConfig.cmake
    opengr-config.cmake

  Add the installation prefix of "OpenGR" to CMAKE_PREFIX_PATH or set
  "OpenGR_DIR" to a directory containing one of the above files.  If "OpenGR"
  provides a separate development package or SDK, be sure it has been
  installed.
`

Here is my CMakeLists.txt

```
cmake_minimum_required(VERSION 3.17)
project(6D_pose)

add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)

## Find catkin macros and libraries
## if COMPONENTS list like find_package(catkin REQUIRED COMPONENTS xyz)
## is used, also find other catkin packages
find_package(catkin REQUIRED COMPONENTS
  roscpp
  darknet_ros_msgs
  std_msgs
  image_transport
  darknet_ros_3d_msgs
  sensor_msgs
  tf2_ros
  tf2_geometry_msgs
  pcl_ros
  pcl_conversions
  roslint
  cv_bridge
)

find_package( OpenCV REQUIRED )
find_package( OpenGR REQUIRED )
find_package( Eigen3 REQUIRED ) 

catkin_package(
  CATKIN_DEPENDS ${PACKAGE_DEPENDENCIES}
  DEPENDS PCL
  INCLUDE_DIRS include
  LIBRARIES ${PROJECT_NAME}
)

include_directories(
  ${catkin_INCLUDE_DIRS}
  ${OpenCV_INCLUDE_DIRS}
  ${OpenGR_INCLUDE_DIR}
)

include_directories(
  include
  ${catkin_INCLUDE_DIRS}
)

add_library(${PROJECT_NAME}
  src/darknet_ros_3d/Darknet3D.cpp
  src/darknet_ros_3d/Darknet3DListener.cpp
)

target_link_libraries( opengr ${PROJECT_NAME} ${catkin_LIBRARIES} ${OpenGR_LiBRARIES} 
)

add_executable(darknet3d_node src/darknet3d_node.cpp)
target_link_libraries(darknet3d_node ${catkin_LIBRARIES} ${PROJECT_NAME})

add_executable(darknet3d_listener_node test/darknet3d_listener_node.cpp)
target_link_libraries(darknet3d_listener_node ${catkin_LIBRARIES} ${PROJECT_NAME})

add_executable(pose_registration main.cpp)
target_link_libraries(${PROJECT_NAME} ${OpenGR_LIBRARIES})

roslint_cpp(
  src/darknet_ros_3d/Darknet3D.cpp include/darknet_ros_3d/Darknet3D.h
  src/darknet_ros_3d/Darknet3DListener.cpp include/darknet_ros_3d/Darknet3DListener.h
  src/darknet3d_node.cpp
)

install(TARGETS ${PROJECT_NAME}
   LIBRARY DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
)

install(DIRECTORY include/${PROJECT_NAME}/
     DESTINATION ${CATKIN_PACKAGE_INCLUDE_DESTINATION})

```

Any help?

**Comment by nmellado** [comment]
Did you set `OpenGR_DIR` to the path where you installed OpenGR ? (`OpenGR_install_dir/lib/cmake`)
See documentation: https://storm-irit.github.io/OpenGR/a00002.html#usage

**Comment by astronaut71** [comment]
I saw the documentation, but now clear how to set `OpenGR_DIR` to the path where O installed OpenGR. Mean I have to set `OpenGR_DIR` in the OpenGR CmakeList.txt or in my own application CmakeList.txt?

**Comment by nmellado** [comment]
When you call cmake to configure your 6D_pose project, you can set the value.
Let say you call cmake for a `build` directory contained in `src`, then:
`cmake -DOpenGR_DIR=/path/to/OpenGR_install_dir/lib/cmake ..`

**Comment by astronaut71** [comment]
But my 6D_pose_project is a ROS catkin package. So I build the package with catkin_make. Im bit confuse now

**Comment by nmellado** [comment]
As described here: http://wiki.ros.org/catkin/commands/catkin_make
`catkin_make` forwards command line arguments to cmake.
So you should be able to do something like `catkin_make -DOpenGR_DIR=/path/to/OpenGR_install_dir/lib/cmake`.

I didn't know OpenGR was referred in a ROS package, could you share its link please ?

**Comment by astronaut71** [comment]
I mean the ROS package I created in the catkin workspace. Not that  OpenGR was referred to in a ROS package. Sorry

**Comment by astronaut71** [comment]
Ok. It works. Thanks so much for the help
