### ISSUE TITLE
Problem with test

### ISSUE THREAD

**Issue by fotsing365** [STORM-IRIT/OpenGR#70]
Hi
Good job. I try to align two point clouds using Super4pcs but  it seems to do nothing and the output file contains only the set which should to be aligned.  What can be the problem?
![Screenshot from 2020-10-07 05-22-33](https://user-images.githubusercontent.com/24406778/95284043-700fda80-085d-11eb-854d-0de8b1f0b6ae.png)

**Comment by nmellado** [comment]
Hi @fotsing365,

Usually this comes from invalid parameter values.
Using 10k samples as you did is very high.
Did you read the documentation? https://storm-irit.github.io/OpenGR/a00012.html

Also, in any case, Super4PCS binary only outputs the transformed point-cloud.

**Comment by nmellado** [comment]
Did you manage to use the program ?
