### ISSUE TITLE
No OpenGRConfig.cmake in latest OpenGR release (outdated)

### ISSUE THREAD

**Issue by maximecharriere** [STORM-IRIT/OpenGR#76]
Hello,
I want to use the [Point Set Processing](https://doc.cgal.org/latest/Point_set_processing_3/index.html) package of the CGAL library, and I need to install OpenGR to use a registartion algorithm.
The example program from CGAL use `find_package(OpenGR)` in his `CMakeLists.txt`. The problem is that after the configuration of OpenGR with cmake and the installation with VisualStudio2019 I don't have the file `OpenGRConfig.cmake` necessary to be recognized as a package.

I have a `Super4PCSConfig.cmake` in `...\OpenGR-1.1.2\build\install\lib\cmake`  but in your [example program](https://storm-irit.github.io/OpenGR/a00002.html#usage) you do `find_package(OpenGR)` and not  `find_package(Super4PCS)`.

What do I need to do for `find_package(OpenGR)` to work ?

**Comment by nmellado** [comment]
Hi,

You should have a OpenGR package, let's try to figure it out...

Could you please post here the following infos:
 - version of the code used (master ?)
 - log of the configure, make and install steps.

Thanks

**Comment by maximecharriere** [comment]
Thank you for your kick replay !

I tried the installation with the [latest release from August 2017](https://github.com/STORM-IRIT/OpenGR/releases/tag/v1.1.2).
Now with the master it work fine. I'm used to get the latest release to have a stable version and not directly the master.

Sorry for the inconvenience.

**Comment by nmellado** [comment]
Thanks, I'll keep the issue open to remind me to add a new release.

**Comment by 821736960** [comment]
> Thank you for your kick replay !
> 
> I tried the installation with the [latest release from August 2017](https://github.com/STORM-IRIT/OpenGR/releases/tag/v1.1.2).
> Now with the master it work fine. I'm used to get the latest release to have a stable version and not directly the master.
> 
> Sorry for the inconvenience.

Hi. bro
I am also doing a project about using opengr-super4pcs algorithm with cagl. I meet the same problem as you did. Would you mind giving me a email and I have some questions. Sorry to bother you.

**Comment by maximecharriere** [comment]
Hello
I can't give you an email, but let's talk in your [issue 84](https://github.com/STORM-IRIT/OpenGR/issues/84)

**Comment by nmellado** [comment]
Fixed, see: https://github.com/STORM-IRIT/OpenGR/releases/tag/v2021.03

**Comment by maximecharriere** [comment]
Nice ! Think that this issue can be closed
