### ISSUE TITLE
Problem with OpenGRConfig.cmake

### ISSUE THREAD

**Issue by maxGimeno** [STORM-IRIT/OpenGR#78]
Hello,

In [the cmake documentation of `find_package`](https://cmake.org/cmake/help/v3.0/command/find_package.html), it is specified that search paths for the config file are, on Unix:
```
<prefix>/(lib/<arch>|lib|share)/cmake/<name>*/          (U)
<prefix>/(lib/<arch>|lib|share)/<name>*/                (U)
<prefix>/(lib/<arch>|lib|share)/<name>*/(cmake|CMake)/  (U)
```
which gives `<prefix>/lib/cmake/opengr/` in my case, on an Ubuntu docker image.
But the current installation path for this file is actually `<prefix>/lib/cmake/`, without the last `opengr` dir, which prevents cmake from automatically finding the configuration file for OpenGR after a simple `make install`.

I think it should be added [here](https://github.com/STORM-IRIT/OpenGR/blob/master/CMakeLists.txt#L234).

Thank you for your time.

**Comment by nmellado** [comment]
Thanks @maxGimeno, are you fine with this proposal ?

**Comment by maxGimeno** [comment]
Yes, perfect ! Thanks !

**Comment by nmellado** [comment]
If you don't mind I'll first merge a PR (I am on it right now) to re-enable CI using GitHub Actions, as travis is currently broken and I cannot ensure that this change of package location is not breaking anything.

**Comment by nmellado** [comment]
Should be fine now.
