### ISSUE TITLE
Potential bug in congruent set exploration

### ISSUE THREAD

**Issue by nmellado** [STORM-IRIT/OpenGR#89]
Initially posted by @joy-yjl: https://github.com/nmellado/Super4PCS/issues/72

https://github.com/STORM-IRIT/OpenGR/blob/c129638491e9f57c0f3f064949bbcc3b007c2f38/src/gr/algorithms/congruentSetExplorationBase.hpp#L350-L352

Suggest: replace `continue` by `break`.

**Comment by nmellado** [comment]
@maximecharriere would you mind to test my fix (#90) ? It is not supposed to affect the quality of the results, but rather speed up the process by cutting the computations when a good solution is found.

**Comment by nmellado** [comment]
@joy-yjl fyi it is not possible to `break` a for loop parallelized with openmp. #90 should to the trick.

**Comment by maximecharriere** [comment]
I have pull, make and install the branch `fix89`
I have tested the registration on a human head containing 1400 vertices via the CGAL interface.
Result using master or fix89 branch were the same.
Time _(only for information, not to be considered as precise)_ : 8373ms with master, 8164ms with fix89
